### ISSUE TITLE
[Proposal] Improve xorfilter.go codebase

### ISSUE THREAD

**Issue by el10savio** [FastFilter/xorfilter#16]
I would like to refactor the xorfilter.go to improve code quality & readability by doing the following:

1. Separate the struct definitions & hashing functions to other files so that it can be made more modular.

2. Reduce the number of lines by combining the same procedures to its own function so that it can be reused easily.

3. Probably add more comments, tests, and benchmarks along the way.

Is there anything else that can be added?

**Comment by lemire** [comment]
Pull request invited. Please run benchmarks before and after: we want to make sure that changes do not come with a performance regression.

**Comment by el10savio** [comment]
Sure, I'll do that 👍
