### ISSUE TITLE
Would you welcome a .Net (C#) implementation?

### ISSUE THREAD

**Issue by IDisposable** [FastFilter/xorfilter#20]
With .Net Core available for free everywhere, would you like a C# implementation?

**Comment by lemire** [comment]
Yes. We could locate it under the FastFilter org as a distinct repo. Note that we have an upcoming upgrade but it is going to be largely the same code.

If you start it, we can then move it under FastFilter if you’d like.

**Comment by thomasmueller** [comment]
The question is answered, so I think we can close the issue.
