### ISSUE TITLE
permit empty filter construction

### ISSUE THREAD

**Issue by rmmh** [FastFilter/xorfilter#21]
`PopulateBinaryFuse8([]uint64{})` currently panics. It should return an error or preferably just construct a trivial tiny filter. Adding `if size == 0 { size = 1 }` is sufficient to prevent panicking.

**Comment by lemire** [comment]
I have added an explicit check. We now return an error given an empty set.

It is nonsensical to try to index an empty set. It indicates an error.

**Comment by lemire** [comment]
Thanks.
