### ISSUE TITLE
Cut releases using tags

### ISSUE THREAD

**Issue by mraerino** [FastFilter/xorfilter#25]
Would you be able to cut release tags so that tooling like dependabot or renovate will not propose an upgrade on every commit?

You could use something like the really nifty [`release-please`](https://github.com/googleapis/release-please) to automate that process along with a nice changelog.

**Comment by lemire** [comment]
That's very reasonable. Would you be willing to produce a pull request?

**Comment by mraerino** [comment]
i'll try using their github action if that sounds useful?

**Comment by lemire** [comment]
@mraerino Sure.

The good thing if you do it with a PR is that you can make sure it meets your expectations. :-)

**Comment by mraerino** [comment]
Opened #26

**Comment by lemire** [comment]
I create release tag v0.1.0.
