### ISSUE TITLE
Implement fuse approach for better compression

### ISSUE THREAD

**Issue by lemire** [FastFilter/xorfilter#8]
See

https://github.com/FastFilter/xor_singleheader/commit/4392b5e03f82037fa61e70cf0ca824ecbe038a65

**Comment by thomasmueller** [comment]
> The Fuse8 xor filter uses the fuse data structure, which requires a large number of keys to be
> operational. Experimentally, this number is somewhere >1e5.

For my (Java) implementation it is currently 190'000. I think there is a workaround: decreasing the load if needed. It would be good to have a formula. According to my test, it eventually works with the following load:

10: 0.879
100: 0.479 .. 0.839
1'000: 0.698
10'000: 0.829
100'000: 0.869

Not sure if the probability is non-linear (as for the xor filter). I didn't read the paper yet, maybe it contains some clue.

**Comment by ayazhafiz** [comment]
I also observed similar in my tests, though not nearly so low for sizes of 100 and 1000. Maybe I got bad samples; I will look again in some time.

**Comment by thomasmueller** [comment]
I just tested with a loop, and don't know the probability at certain sizes yet. So my numbers are just the points where I was lucky. 

Unless there is a formula we can use, then we need to run many tests at different sizes, to get the approximate probabilities.
